#!/usr/bin/env python3
"""Post a simple Instagram photo using a persisted instagrapi session.

Usage:
  python agents/scripts/instagram_post_test.py \
    --username <instagram_username> \
    --password <instagram_password> \
    --caption "Test post from UMHackathon2026"
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path

from instagrapi import Client


def _create_test_image(path: Path) -> None:
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (1080, 1080), color=(16, 18, 27))
    draw = ImageDraw.Draw(img)
    draw.rectangle([(90, 90), (990, 990)], outline=(65, 212, 158), width=8)
    draw.text((140, 240), "UMHackathon2026", fill=(230, 235, 245))
    draw.text((140, 320), "instagrapi smoke test", fill=(230, 235, 245))
    draw.text((140, 400), "If you see this, session posting works.", fill=(190, 205, 235))
    img.save(path, format="JPEG", quality=95)


def _require(value: str | None, flag_name: str) -> str:
    if value:
        return value
    raise ValueError(f"missing {flag_name}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Post a test photo using instagrapi session")
    parser.add_argument("--username", default=os.getenv("INSTAGRAM_USERNAME"))
    parser.add_argument("--password", default=os.getenv("INSTAGRAM_PASSWORD"))
    parser.add_argument(
        "--session-file",
        default=str(Path(".instagram-test-session.json")),
        help="Path to session settings JSON generated by instagram_session_test.py",
    )
    parser.add_argument(
        "--caption",
        default="Automated test post from UMHackathon2026",
        help="Caption for uploaded post",
    )
    parser.add_argument(
        "--image",
        default="",
        help="Optional path to image. If omitted, a temporary test image is generated.",
    )
    args = parser.parse_args()

    try:
        username = _require(args.username, "--username or INSTAGRAM_USERNAME")
        password = _require(args.password, "--password or INSTAGRAM_PASSWORD")
    except ValueError as e:
        print(f"[error] {e}")
        return 2

    session_path = Path(args.session_file)
    if not session_path.exists():
        print(f"[error] session file not found: {session_path}")
        print("Run instagram_session_test.py first.")
        return 2

    remove_temp_image = False
    if args.image:
        image_path = Path(args.image)
        if not image_path.exists():
            print(f"[error] image not found: {image_path}")
            return 2
    else:
        fd, tmp_name = tempfile.mkstemp(prefix="ig-post-test-", suffix=".jpg")
        os.close(fd)
        image_path = Path(tmp_name)
        _create_test_image(image_path)
        remove_temp_image = True

    cl = Client()
    try:
        print(f"[1/3] Loading session from {session_path} ...")
        cl.load_settings(str(session_path))

        print(f"[2/3] Validating login as @{username} ...")
        if not cl.login(username, password):
            print("[error] login() failed while using loaded session")
            return 1

        print(f"[3/3] Uploading photo {image_path} ...")
        media = cl.photo_upload(str(image_path), args.caption)
        print(f"[ok] Posted successfully. media_pk={media.pk}, media_id={media.id}")
        return 0
    finally:
        if remove_temp_image:
            try:
                image_path.unlink(missing_ok=True)
            except OSError:
                pass


if __name__ == "__main__":
    sys.exit(main())
