#!/usr/bin/env python3
"""Generate AI images with OpenAI and post them to Instagram via instagrapi.

Smoke-test oriented script:
1) Load persisted Instagram session.
2) Validate login.
3) Generate N images from prompt via OpenAI Images API.
4) Upload generated images as one Instagram carousel post (slides).
"""

from __future__ import annotations

import argparse
import base64
import io
import os
import sys
import tempfile
from pathlib import Path

import httpx
from instagrapi import Client
from openai import OpenAI
from PIL import Image


def _require(value: str | None, flag_name: str) -> str:
    if value:
        return value
    raise ValueError(f"missing {flag_name}")


def _generate_image_bytes(client: OpenAI, model: str, size: str, prompt: str) -> bytes:
    resp = client.images.generate(
        model=model,
        prompt=prompt,
        size=size,
    )
    item = resp.data[0]
    b64_json = getattr(item, "b64_json", None)
    if b64_json:
        return base64.b64decode(b64_json)

    url = getattr(item, "url", None)
    if url:
        with httpx.Client(timeout=120) as http:
            r = http.get(url)
            r.raise_for_status()
            return r.content

    raise RuntimeError("OpenAI image response did not include b64_json or url")


def _prepare_instagram_slide(image_bytes: bytes, idx: int) -> Path:
    """Convert generated image to IG carousel-safe JPEG 4:5 without cropping.

    Strategy:
    - Fit the generated image inside 1080x1350 (4:5) canvas.
    - Preserve full content with letterboxing/padding, never crop.
    - Save as JPEG, because album_upload is most reliable with JPG files.
    """
    target_w, target_h = 1080, 1350
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")

    # Keep full image visible (no crop); pad to 4:5 canvas.
    ratio = min(target_w / img.width, target_h / img.height)
    resized = img.resize((int(img.width * ratio), int(img.height * ratio)))

    canvas = Image.new("RGB", (target_w, target_h), color=(245, 246, 250))
    x = (target_w - resized.width) // 2
    y = (target_h - resized.height) // 2
    canvas.paste(resized, (x, y))

    fd, tmp_name = tempfile.mkstemp(prefix=f"ig-ai-slide-{idx + 1}-", suffix=".jpg")
    os.close(fd)
    out = Path(tmp_name)
    canvas.save(out, format="JPEG", quality=95, optimize=True)
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate AI images and post them to Instagram")
    parser.add_argument("--username", default=os.getenv("INSTAGRAM_USERNAME"))
    parser.add_argument("--password", default=os.getenv("INSTAGRAM_PASSWORD"))
    parser.add_argument(
        "--session-file",
        default=str(Path(".instagram-test-session.json")),
        help="Session settings JSON generated by instagram_session_test.py",
    )
    parser.add_argument(
        "--count",
        type=int,
        default=1,
        help="How many images to generate (uploaded as one carousel when >1)",
    )
    parser.add_argument(
        "--prompt",
        default="Fresh milk sale poster, Malaysian style, highlight price MYR 10",
        help="Prompt used to generate images",
    )
    parser.add_argument(
        "--caption",
        default="Fresh milk promo - only MYR 10. #freshmilk #promo #malaysia",
        help="Caption to use for each posted image",
    )
    parser.add_argument(
        "--image-model",
        default=os.getenv("OPENAI_IMAGE_MODEL", "gpt-image-1"),
        help="OpenAI image model",
    )
    parser.add_argument(
        "--image-size",
        default=os.getenv("OPENAI_IMAGE_SIZE", "1024x1536"),
        help="OpenAI image size, e.g. 1024x1024",
    )
    args = parser.parse_args()

    if args.count < 1:
        print("[error] --count must be >= 1")
        return 2

    try:
        username = _require(args.username, "--username or INSTAGRAM_USERNAME")
        password = _require(args.password, "--password or INSTAGRAM_PASSWORD")
        openai_key = _require(os.getenv("OPENAI_IMAGE_KEY"), "OPENAI_IMAGE_KEY")
    except ValueError as e:
        print(f"[error] {e}")
        return 2

    session_path = Path(args.session_file)
    if not session_path.exists():
        print(f"[error] session file not found: {session_path}")
        print("Run instagram_session_test.py first.")
        return 2

    image_base_url = os.getenv("OPENAI_IMAGE_API_BASE", "https://api.openai.com/v1")
    openai_client = OpenAI(api_key=openai_key, base_url=image_base_url)

    ig = Client()
    print(f"[1/4] Loading Instagram session from {session_path} ...")
    ig.load_settings(str(session_path))
    print(f"[2/4] Validating Instagram login as @{username} ...")
    if not ig.login(username, password):
        print("[error] Instagram login failed")
        return 1

    generated_files: list[Path] = []
    try:
        print(f"[3/4] Generating {args.count} image(s) with {args.image_model} ...")
        for idx in range(args.count):
            variant_prompt = (
                f"{args.prompt}\n"
                f"Variation {idx + 1} of {args.count}. "
                "Create a unique composition and text layout. "
                "Keep key text and product fully inside center safe area with generous margins."
            )
            img_bytes = _generate_image_bytes(
                client=openai_client,
                model=args.image_model,
                size=args.image_size,
                prompt=variant_prompt,
            )
            path = _prepare_instagram_slide(img_bytes, idx)
            generated_files.append(path)
            print(f"    [ok] generated slide {path}")

        print("[4/4] Uploading generated image(s) to Instagram ...")
        if len(generated_files) == 1:
            media = ig.photo_upload(str(generated_files[0]), args.caption)
            print(f"    [ok] posted single image media_id={media.id}")
        else:
            media = ig.album_upload([str(p) for p in generated_files], args.caption)
            print(
                "    [ok] posted carousel with "
                f"{len(generated_files)} slides media_id={media.id}"
            )
    finally:
        for path in generated_files:
            try:
                path.unlink(missing_ok=True)
            except OSError:
                pass

    print("[ok] AI image generation + Instagram posting flow completed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
