/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayOrderIdRouteImport } from './routes/pay/$orderId'
import { Route as BusinessCodeSettingsRouteImport } from './routes/$businessCode/settings'
import { Route as BusinessCodeSalesRouteImport } from './routes/$businessCode/sales'
import { Route as BusinessCodeProductsRouteImport } from './routes/$businessCode/products'
import { Route as BusinessCodeInboxRouteImport } from './routes/$businessCode/inbox'
import { Route as BusinessCodeGoalsRouteImport } from './routes/$businessCode/goals'
import { Route as BusinessCodeDashboardRouteImport } from './routes/$businessCode/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BusinessCodeChannelsInstagramRouteImport } from './routes/$businessCode/channels/instagram'
import { Route as BusinessCodeAgentsAgentTypeRouteImport } from './routes/$businessCode/agents/$agentType'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeSettingsRoute = BusinessCodeSettingsRouteImport.update({
  id: '/$businessCode/settings',
  path: '/$businessCode/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeSalesRoute = BusinessCodeSalesRouteImport.update({
  id: '/$businessCode/sales',
  path: '/$businessCode/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeProductsRoute = BusinessCodeProductsRouteImport.update({
  id: '/$businessCode/products',
  path: '/$businessCode/products',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeInboxRoute = BusinessCodeInboxRouteImport.update({
  id: '/$businessCode/inbox',
  path: '/$businessCode/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeGoalsRoute = BusinessCodeGoalsRouteImport.update({
  id: '/$businessCode/goals',
  path: '/$businessCode/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeDashboardRoute = BusinessCodeDashboardRouteImport.update({
  id: '/$businessCode/dashboard',
  path: '/$businessCode/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeChannelsInstagramRoute =
  BusinessCodeChannelsInstagramRouteImport.update({
    id: '/$businessCode/channels/instagram',
    path: '/$businessCode/channels/instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const BusinessCodeAgentsAgentTypeRoute =
  BusinessCodeAgentsAgentTypeRouteImport.update({
    id: '/$businessCode/agents/$agentType',
    path: '/$businessCode/agents/$agentType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$businessCode/dashboard': typeof BusinessCodeDashboardRoute
  '/$businessCode/goals': typeof BusinessCodeGoalsRoute
  '/$businessCode/inbox': typeof BusinessCodeInboxRoute
  '/$businessCode/products': typeof BusinessCodeProductsRoute
  '/$businessCode/sales': typeof BusinessCodeSalesRoute
  '/$businessCode/settings': typeof BusinessCodeSettingsRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/$businessCode/agents/$agentType': typeof BusinessCodeAgentsAgentTypeRoute
  '/$businessCode/channels/instagram': typeof BusinessCodeChannelsInstagramRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$businessCode/dashboard': typeof BusinessCodeDashboardRoute
  '/$businessCode/goals': typeof BusinessCodeGoalsRoute
  '/$businessCode/inbox': typeof BusinessCodeInboxRoute
  '/$businessCode/products': typeof BusinessCodeProductsRoute
  '/$businessCode/sales': typeof BusinessCodeSalesRoute
  '/$businessCode/settings': typeof BusinessCodeSettingsRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/$businessCode/agents/$agentType': typeof BusinessCodeAgentsAgentTypeRoute
  '/$businessCode/channels/instagram': typeof BusinessCodeChannelsInstagramRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$businessCode/dashboard': typeof BusinessCodeDashboardRoute
  '/$businessCode/goals': typeof BusinessCodeGoalsRoute
  '/$businessCode/inbox': typeof BusinessCodeInboxRoute
  '/$businessCode/products': typeof BusinessCodeProductsRoute
  '/$businessCode/sales': typeof BusinessCodeSalesRoute
  '/$businessCode/settings': typeof BusinessCodeSettingsRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/$businessCode/agents/$agentType': typeof BusinessCodeAgentsAgentTypeRoute
  '/$businessCode/channels/instagram': typeof BusinessCodeChannelsInstagramRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$businessCode/dashboard'
    | '/$businessCode/goals'
    | '/$businessCode/inbox'
    | '/$businessCode/products'
    | '/$businessCode/sales'
    | '/$businessCode/settings'
    | '/pay/$orderId'
    | '/$businessCode/agents/$agentType'
    | '/$businessCode/channels/instagram'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$businessCode/dashboard'
    | '/$businessCode/goals'
    | '/$businessCode/inbox'
    | '/$businessCode/products'
    | '/$businessCode/sales'
    | '/$businessCode/settings'
    | '/pay/$orderId'
    | '/$businessCode/agents/$agentType'
    | '/$businessCode/channels/instagram'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/$businessCode/dashboard'
    | '/$businessCode/goals'
    | '/$businessCode/inbox'
    | '/$businessCode/products'
    | '/$businessCode/sales'
    | '/$businessCode/settings'
    | '/pay/$orderId'
    | '/$businessCode/agents/$agentType'
    | '/$businessCode/channels/instagram'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BusinessCodeDashboardRoute: typeof BusinessCodeDashboardRoute
  BusinessCodeGoalsRoute: typeof BusinessCodeGoalsRoute
  BusinessCodeInboxRoute: typeof BusinessCodeInboxRoute
  BusinessCodeProductsRoute: typeof BusinessCodeProductsRoute
  BusinessCodeSalesRoute: typeof BusinessCodeSalesRoute
  BusinessCodeSettingsRoute: typeof BusinessCodeSettingsRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  BusinessCodeAgentsAgentTypeRoute: typeof BusinessCodeAgentsAgentTypeRoute
  BusinessCodeChannelsInstagramRoute: typeof BusinessCodeChannelsInstagramRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/settings': {
      id: '/$businessCode/settings'
      path: '/$businessCode/settings'
      fullPath: '/$businessCode/settings'
      preLoaderRoute: typeof BusinessCodeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/sales': {
      id: '/$businessCode/sales'
      path: '/$businessCode/sales'
      fullPath: '/$businessCode/sales'
      preLoaderRoute: typeof BusinessCodeSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/products': {
      id: '/$businessCode/products'
      path: '/$businessCode/products'
      fullPath: '/$businessCode/products'
      preLoaderRoute: typeof BusinessCodeProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/inbox': {
      id: '/$businessCode/inbox'
      path: '/$businessCode/inbox'
      fullPath: '/$businessCode/inbox'
      preLoaderRoute: typeof BusinessCodeInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/goals': {
      id: '/$businessCode/goals'
      path: '/$businessCode/goals'
      fullPath: '/$businessCode/goals'
      preLoaderRoute: typeof BusinessCodeGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/dashboard': {
      id: '/$businessCode/dashboard'
      path: '/$businessCode/dashboard'
      fullPath: '/$businessCode/dashboard'
      preLoaderRoute: typeof BusinessCodeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/channels/instagram': {
      id: '/$businessCode/channels/instagram'
      path: '/$businessCode/channels/instagram'
      fullPath: '/$businessCode/channels/instagram'
      preLoaderRoute: typeof BusinessCodeChannelsInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/agents/$agentType': {
      id: '/$businessCode/agents/$agentType'
      path: '/$businessCode/agents/$agentType'
      fullPath: '/$businessCode/agents/$agentType'
      preLoaderRoute: typeof BusinessCodeAgentsAgentTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BusinessCodeDashboardRoute: BusinessCodeDashboardRoute,
  BusinessCodeGoalsRoute: BusinessCodeGoalsRoute,
  BusinessCodeInboxRoute: BusinessCodeInboxRoute,
  BusinessCodeProductsRoute: BusinessCodeProductsRoute,
  BusinessCodeSalesRoute: BusinessCodeSalesRoute,
  BusinessCodeSettingsRoute: BusinessCodeSettingsRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  BusinessCodeAgentsAgentTypeRoute: BusinessCodeAgentsAgentTypeRoute,
  BusinessCodeChannelsInstagramRoute: BusinessCodeChannelsInstagramRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
