/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessCodeDashboardRouteImport } from './routes/$businessCode.dashboard'
import { Route as BusinessCodeProductsRouteImport } from './routes/$businessCode.products'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeDashboardRoute = BusinessCodeDashboardRouteImport.update({
  id: '/$businessCode/dashboard',
  path: '/$businessCode/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCodeProductsRoute = BusinessCodeProductsRouteImport.update({
  id: '/$businessCode/products',
  path: '/$businessCode/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$businessCode/dashboard': typeof BusinessCodeDashboardRoute
  '/$businessCode/products': typeof BusinessCodeProductsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$businessCode/dashboard': typeof BusinessCodeDashboardRoute
  '/$businessCode/products': typeof BusinessCodeProductsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$businessCode/dashboard': typeof BusinessCodeDashboardRoute
  '/$businessCode/products': typeof BusinessCodeProductsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$businessCode/dashboard' | '/$businessCode/products' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/$businessCode/dashboard' | '/$businessCode/products' | '/api/auth/$'
  id: '__root__' | '/' | '/login' | '/$businessCode/dashboard' | '/$businessCode/products' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BusinessCodeDashboardRoute: typeof BusinessCodeDashboardRoute
  BusinessCodeProductsRoute: typeof BusinessCodeProductsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/dashboard': {
      id: '/$businessCode/dashboard'
      path: '/$businessCode/dashboard'
      fullPath: '/$businessCode/dashboard'
      preLoaderRoute: typeof BusinessCodeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessCode/products': {
      id: '/$businessCode/products'
      path: '/$businessCode/products'
      fullPath: '/$businessCode/products'
      preLoaderRoute: typeof BusinessCodeProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BusinessCodeDashboardRoute: BusinessCodeDashboardRoute,
  BusinessCodeProductsRoute: BusinessCodeProductsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
